services:
  db:
    image: postgres:18
    container_name: lms_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lms
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/1_init.sql
      - ./perf_data.sql:/docker-entrypoint-initdb.d/2_perf_data.sql